### ISSUE TITLE
lgnn training time

### ISSUE THREAD

**Issue by yCobanoglu** [zhengdao-chen/GNN4CD#10]
Generating the lgnn adjacencies for the hierachy takes forever. `np.dot(QQ, QQ)` in file `load.py` line 19 is the bottleneck. This is a very large matmul 6000 times (for 6000 training samples) and only possible to perform on the cpu (due to vram constraints) ?
How long does it take to train the lgnn ? How did you pull it off for the paper ?

**Comment by zhengdao-chen** [comment]
It's been a few years since I trained the models and I don't remember exactly how long it took. The experiments did take a while but would eventually finish... Are these graphs generated under the same configurations as described in the paper, for example?

**Comment by yCobanoglu** [comment]
Ok good to know thanks !
