### ISSUE TITLE
相关环境依赖 以及 运行报错

### ISSUE THREAD

**Issue by wjlpku** [zhengdao-chen/GNN4CD#3]
您好，能不能说明一下相关环境依赖，比如pytorch版本， python版本。
以及尝试运行的时候会报错
 File "main_gnn.py", line 9, in <module>
    from models import GNN_bcd, GNN_multiclass
ModuleNotFoundError: No module named 'models'
不知道这里的models是哪个库里面的？

**Comment by cuent** [comment]
Same problem here. Could you please upload/describe where the `models` module comes from?

**Comment by zhengdao-chen** [comment]
I am very sorry about this delay. I realized that I didn't upload the correct models.py file initially, and later made a change to the repo. I wonder if it is working now?
