### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by haory-95** [zhengdao-chen/GNN4CD#6]
你好，可否请你详细说说这个有监督的社区检测问题和一般的节点分类问题之间的区别在哪？

**Comment by zhengdao-chen** [comment]
你好，一个区别是社区检测问题的节点类别是permutation-invariant的，因此比如spectral methods可以发挥作用。

**Comment by haory-95** [comment]
你好，感谢你的解答，请问我可否理解成你这篇文章的任务是在图上区分出固定数目的不同社区，而不是预测这些社区明确的label?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhengdao-chen/GNN4CD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhengdao-chen/GNN4CD] 问题请教 (#6)





 
你好，一个区别是社区检测问题的节点类别是permutation-invariant的，因此比如spectral methods可以发挥作用。

**Comment by zhengdao-chen** [comment]
是的

**Comment by haory-95** [comment]
你好，我反复看了原文，都没理解Sc和π的真正含义，然后在网上看到了一篇对于你这篇文章的学习笔记。我想请问一下身为原文作者，你觉得这个例子举的合适吗？谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhengdao-chen/GNN4CD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 晚上8:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhengdao-chen/GNN4CD] 问题请教 (#6)





 
是的
