### ISSUE TITLE
real data sets

### ISSUE THREAD

**Issue by xinyue96** [zhengdao-chen/GNN4CD#8]
Hi, could you also provide your preprocessed real dataset (Amazon, DBLP, Youtube)?

**Comment by cknnsshxs** [comment]
Similar question, or could you provide the code of the experiments on the real datasets(or code of how to process the snap real datasets)?Thanks in advance!

**Comment by afafe1** [comment]
please could you provide for us the implementation for real snap dataset. Thank you in advance!

**Comment by zhengdao-chen** [comment]
Thanks for the questions from you all, and I am very sorry that the Python implementation for the experiments on the real datasets is no longer kept, though an earlier implementation in Lua can be found at https://github.com/joanbruna/GNN_community.git, which includes the code for the real datasets. Hope that helps, and apologies for the confusion and inconvenience!
