### ISSUE TITLE
Hi how to use your code over realworld dataset?

### ISSUE THREAD

**Issue by Luo-Yihong** [zhengdao-chen/GNN4CD#9]
I found out that your code only could test model over "generated" dataset? Could you release code that could test model over real world dataset?

**Comment by zhengdao-chen** [comment]
Thanks for the question, and I am very sorry that the Python implementation for the experiments on the real datasets is no longer kept, though an earlier implementation in Lua can be found at https://github.com/joanbruna/GNN_community.git, which includes the code for the real datasets. Hope that helps, and apologies for the confusion and inconvenience!
